<?php

namespace App\Constants\ShowFunctionKinds;

final class ShowFunctionKind{
    public const UNDEFINED = 0;
    public const USER_LOGIN = 1;
    public const ADMIN_LOGIN = 2;
    public const REGISTER = 3;
    public const SHOW_EMAIL_VERIFICATION_FOR_USER = 4;
    public const SHOW_EMAIL_VERIFICATION_FOR_ADMIN = 5;
    public const ATTENDANCE = 6;
    public const ATTENDANCE_LIST = 7;
    public const ATTENDANCE_DETAIL_ID_VIA_ATTENDANCE_LIST = 8;
    public const ATTENDANCE_DETAIL_ID_VIA_STAMP_CORRECTION_REQUEST_LIST_FOR_USER = 9;
    public const STAMP_CORRECTION_REQUEST_LIST_FOR_USER = 10;
    public const STAMP_CORRECTION_REQUEST_LIST_FOR_ADMIN = 11;
    public const ADMIN_ATTENDANCE_LIST = 12;
    public const ADMIN_ATTENDANCE_ID_VIA_ADMIN_ATTENDANCE_LIST = 13;
    public const ADMIN_ATTENDANCE_ID_VIA_ADMIN_ATTENDANCE_STAFF_ID = 14;
    public const ADMIN_STAFF_LIST = 15;
    public const ADMIN_ATTENDANCE_STAFF_ID = 16;
    public const STAMP_CORRECTION_REQUEST_APPROVE_ATTENDANCE_CORRECT_REQUEST_ID = 17;

     public static function toArray()
    {
        return [
            'UNDEFINED' => self::UNDEFINED,
            'USER_LOGIN' => self::USER_LOGIN,
            'ADMIN_LOGIN' => self::ADMIN_LOGIN,
            'REGISTER' => self::REGISTER,
            'SHOW_EMAIL_VERIFICATION_FOR_USER' => self::SHOW_EMAIL_VERIFICATION_FOR_USER,
            'SHOW_EMAIL_VERIFICATION_FOR_ADMIN' => self::SHOW_EMAIL_VERIFICATION_FOR_ADMIN,
            'ATTENDANCE' => self::ATTENDANCE,
            'ATTENDANCE_LIST' => self::ATTENDANCE_LIST,
            'ATTENDANCE_DETAIL_ID_VIA_ATTENDANCE_LIST' 
                => self::ATTENDANCE_DETAIL_ID_VIA_ATTENDANCE_LIST,
            'ATTENDANCE_DETAIL_ID_VIA_STAMP_CORRECTION_REQUEST_LIST_FOR_USER' 
                => self::ATTENDANCE_DETAIL_ID_VIA_STAMP_CORRECTION_REQUEST_LIST_FOR_USER,
            'STAMP_CORRECTION_REQUEST_LIST_FOR_USER' => self::STAMP_CORRECTION_REQUEST_LIST_FOR_USER,
            'STAMP_CORRECTION_REQUEST_LIST_FOR_ADMIN' => self::STAMP_CORRECTION_REQUEST_LIST_FOR_ADMIN,
            'ADMIN_ATTENDANCE_LIST' => self::ADMIN_ATTENDANCE_LIST,
            'ADMIN_ATTENDANCE_ID_VIA_ADMIN_ATTENDANCE_LIST' => self::ADMIN_ATTENDANCE_ID_VIA_ADMIN_ATTENDANCE_LIST,
            'ADMIN_ATTENDANCE_ID_VIA_ADMIN_ATTENDANCE_STAFF_ID'
                => self::ADMIN_ATTENDANCE_ID_VIA_ADMIN_ATTENDANCE_STAFF_ID,
            'ADMIN_STAFF_LIST' => self::ADMIN_STAFF_LIST,
            'ADMIN_ATTENDANCE_STAFF_ID' => self::ADMIN_ATTENDANCE_STAFF_ID,
            'STAMP_CORRECTION_REQUEST_APPROVE_ATTENDANCE_CORRECT_REQUEST_ID'
                => self::STAMP_CORRECTION_REQUEST_APPROVE_ATTENDANCE_CORRECT_REQUEST_ID,
        ];
    }


}
